_wandb:
    value:
        cli_version: 0.21.3
        e:
            fr4pau2yq1zsghmla4xdgec2ibk04yid:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "4294967296"
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494353338368"
                        used: "287027142656"
                email: gauthier.bassereau@gmail.com
                executable: /opt/anaconda3/envs/ML/bin/python3
                git:
                    commit: 28757d40f9ef70fb916612a1f8b0aa7a582cf4ea
                    remote: https://github.com/Gautthegoat/A-R-G-O-S.git
                host: MacBook-Pro-5.local
                memory:
                    total: "19327352832"
                os: macOS-26.0-arm64-arm-64bit
                program: -m source.pipelines.train_decoder
                python: CPython 3.10.15
                root: "/Users/gauthierbassereau/Library/Mobile Documents/com~apple~CloudDocs/Perso \U0001F3E0/A-R-G-O-S"
                startedAt: "2025-09-14T11:10:07.123356Z"
                writerId: fr4pau2yq1zsghmla4xdgec2ibk04yid
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
            "2":
                - 1
                - 41
                - 49
                - 51
            "3":
                - 13
                - 16
                - 61
            "4": 3.10.15
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
batch_size:
    value: 2
device:
    value: mps
lr:
    value: 0.0001
